package souther.gradle;

import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.zip.ZipFile;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Kotlin beside the model.
 *
 * <p>The arrangement this plugin replaces needed a source set of its own for this, because Gradle's
 * Kotlin plugin compiles Kotlin before Java within one source set — the wrong order when the Kotlin
 * side depends on the generated bytecode. That was a fact about Gradle every user had to learn.
 * Here the generated classes are on the source set's compile class path, so the ordering follows
 * from the class path rather than from an arrangement.
 */
class KotlinBesideTheModelTest {

    @Test
    void kotlinCompilesAgainstTheModelWithoutASourceSetOfItsOwn(@TempDir Path dir)
            throws IOException {
        Files.writeString(dir.resolve("settings.gradle.kts"), """
                rootProject.name = "with-kotlin"
                """);
        Files.writeString(dir.resolve("build.gradle.kts"), """
                plugins {
                    kotlin("jvm") version "2.2.20"
                    id("org.souther-lang.souther")
                }

                repositories {
                    mavenCentral()
                    mavenLocal()
                    %s
                }

                // Kotlin has no JVM target 25 yet and falls back to 24, which Gradle then refuses
                // as inconsistent with javac's default. Both are said here so the test is about the
                // ordering rather than about that.
                java {
                    sourceCompatibility = JavaVersion.VERSION_24
                    targetCompatibility = JavaVersion.VERSION_24
                }

                %s
                """.formatted(extraRepository(), TestedSouther.block()));
        Path model = Files.createDirectories(dir.resolve("src/main/souther"));
        Files.writeString(model.resolve("money.sou"), """
                module shared.money exposing ( Amount )

                data Amount = Int
                    invariant value >= 0
                """);
        Path kotlin = Files.createDirectories(dir.resolve("src/main/kotlin/app"));
        Files.writeString(kotlin.resolve("Purses.kt"), """
                package app

                import shared.money.Amount
                import souther.runtime.InvariantFailure
                import souther.runtime.Result

                object Purses {
                    fun of(n: Long): Result<Amount, InvariantFailure> = Amount.__construct(n)
                }
                """);

        BuildResult built = GradleRunner.create()
                .withProjectDir(dir.toFile())
                .withPluginClasspath()
                .withArguments("jar")
                .build();

        assertTrue(built.getOutput().contains("BUILD SUCCESSFUL"), built.getOutput());
        try (ZipFile jar = new ZipFile(dir.resolve("build/libs/with-kotlin.jar").toFile())) {
            assertNotNull(jar.getEntry("app/Purses.class"));
            assertNotNull(jar.getEntry("shared/money/Amount.class"));
        }
    }

    /**
     * A repository to read Souther from besides the released one, for a Souther built from source.
     * Empty unless -PsoutherRepo=<path> is passed, so the default run resolves the released Souther
     * the same way a project that applies this plugin does.
     */
    private static String extraRepository() {
        String repository = System.getProperty("souther.repo");
        return repository == null ? "" : "maven { url = uri(\"" + repository + "\") }";
    }
}
